name = "talking-server"
main = "src/index.js"
compatibility_date = "2025-09-09"

[[kv_namespaces]]
binding = "POSTS_KV"
id = "a57a8466d904430db4ee1aee3f8b32d6"

[[r2_buckets]]
binding = "POST_BUCKET"
bucket_name = "talking"

[vars]
GITHUB_CLIENT_ID = "Ov23liFji9Z0yMQlsLw0"
GITHUB_CLIENT_SECRET = "62084e8e59696dd00a0b41544a3d72ddc3c2bf63"
ADMIN_USERS = 'kemiaofxjun,Kemeow815'
